### ISSUE TITLE
Improving README

### ISSUE THREAD

**Issue by davidcostadev** [team-gryffindor/MentorMatch#126]
I see your project, but I don't what is about?

And I think that we can improve the README with the following topics:

- What is the Project?
- The Objective of the project?
- For whom is the project?
- What is required to know to contribute to this project?
- How to install?
- How to Contribute?
- What is the License of this project?

**Comment by arjunloges** [comment]
Hey David! 
First and foremost, thank you for you constructive comment! Our application is still very much in development stage, the dev team is making substantial improvements by the day. We will have a informative README up as soon as the application is done with stage testing and ready for deployment! Stay tuned for exciting new updates!
